language: php
sudo: false

php:
    - "7.0"
    - "5.6"
    - "5.5"
    - "5.4"
    - "5.3"
    - "hhvm"

matrix:
    include:
        - php: 5.2
          dist: precise
        - php: 5.3
          dist: precise
    fast_finish: true
    allow_failures:
        - php: "hhvm"

install:
    - composer self-update
    - composer update

script:
    - ./phpunit.sh
